# This workflow will build and test a Go project.
# It includes a step to initialize a Go module, as one is missing from the repository.

name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22' # Using a recent stable version of Go

    - name: Initialize Go module
      run: go mod init github.com/KunalKumar-1/http-server

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
